name: Build SKIA
on: 
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-build-skia]

jobs:
  build:
    runs-on: [self-hosted, Tallinn, Skia]
    env:
      WORKING_DIRECTORY: ./
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Get current branch
        id: get-branch
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Print current branch
        run: echo "Current branch is ${{ env.BRANCH_NAME }}"

      - name: Get submodule branches
        run: |
          git submodule foreach '
          echo "Submodule path: $sm_path"
          echo "Submodule branch: $(git rev-parse --abbrev-ref HEAD)"
          '
      - name: Install root node dependencies
        run: yarn

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r22b

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install root node dependencies
        run: yarn

      - name: Build Skia
        working-directory: ${{ env.WORKING_DIRECTORY }}/
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: yarn build-skia

      - name: Upload artifacts - Android arm
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: skia-android-arm
          path: |
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm/libskia.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm/libskshaper.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm/libsvg.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm/libskottie.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm/libsksg.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm/libskparagraph.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm/libskunicode.a

      - name: Upload artifacts - Android arm64
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: skia-android-arm-64
          path: |
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm64/libskia.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm64/libskshaper.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm64/libsvg.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm64/libskottie.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm64/libsksg.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm64/libskparagraph.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/arm64/libskunicode.a

      - name: Upload artifacts - Android x86
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: skia-android-arm-x86
          path: |
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x86/libskia.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x86/libskshaper.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x86/libsvg.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x86/libskottie.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x86/libsksg.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x86/libskparagraph.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x86/libskunicode.a

      - name: Upload artifacts - Android x64
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: skia-android-arm-x64
          path: |
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x64/libskia.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x64/libskshaper.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x64/libsvg.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x64/libskottie.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x64/libsksg.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x64/libskparagraph.a
            ${{ env.WORKING_DIRECTORY }}/externals/skia/out/android/x64/libskunicode.a

      - name: Upload artifacts - iOS xcframeworks
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: skia-ios-xcframeworks
          path: |
            ${{ env.WORKING_DIRECTORY }}/package/libs/ios/libskia.xcframework
            ${{ env.WORKING_DIRECTORY }}/package/libs/ios/libskshaper.xcframework
            ${{ env.WORKING_DIRECTORY }}/package/libs/ios/libsvg.xcframework
            ${{ env.WORKING_DIRECTORY }}/package/libs/ios/libskottie.xcframework
            ${{ env.WORKING_DIRECTORY }}/package/libs/ios/libsksg.xcframework
            ${{ env.WORKING_DIRECTORY }}/package/libs/ios/libskparagraph.xcframework
            ${{ env.WORKING_DIRECTORY }}/package/libs/ios/libskunicode.xcframework

      - name: Trigger build-npm workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          event-type: trigger-build-npm