name: cpplint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  cpplint:
    runs-on: [self-hosted, Tallinn, Skia]
    steps:
    - uses: actions/checkout@v1
    - run: pip3 install cpplint
    - run: cpplint --linelength=230 --filter=-legal/copyright,-whitespace/indent,-whitespace/comments,-whitespace/ending_newline,-build/include_order,-runtime/references,-readability/todo,-whitespace/blank_line,-whitespace/todo,-runtime/int,-build/c++11,-whitespace/parens --exclude=package/cpp/skia --exclude=package/ios --exclude=package/android/build --exclude=package/node_modules --recursive package
