name: Visual Regression - iOS

on: workflow_dispatch

jobs:
  run-visual-regression-ios:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Get Runner Information
        run: /usr/bin/xcodebuild -version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install root node dependencies
        run: yarn

      - name: Download Skia Binary Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "build-skia.yml"
          path: artifacts

      - name: Copy Artifacts to libs folder
        run: yarn workflow-copy-libs

      - name: Copy Skia Headers
        run: yarn copy-skia-headers

      - name: Install Package
        run: yarn
        working-directory: ./example

      - name: Install Example
        run: yarn
        working-directory: ./example

      - name: Install CocoaPods
        run: gem install cocoapods -v 1.11.0

      - uses: actions/cache@v2
        with:
          path: ./example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        run: pod install
        working-directory: ./example/ios

      - uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 14 Pro'
          os_version: '>=16.0'

      - name: Run Owl Build
        run: yarn owl:build:ios
        working-directory: ./example/ios

      - name: Run Owl Test
        run: yarn owl:test:ios
        working-directory: ./example/ios

      - name: Store screenshots and report as artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: owl-results
          path: ./.owl